name: "📰 The Lytton Tribune"

on:
  schedule:
    - cron: "38 */3 * * *"

env:
  RUN_ID: -1
  RUN_TIMING: 5

jobs:
  post_lytton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate timing
        run: |
          echo "RUN_ID=$((${{ github.run_number }} % $RUN_TIMING))" >> "$GITHUB_ENV"
      - name: Install poetry
        if: env.RUN_ID == 0
        run: pipx install poetry
      - name: Set up Python
        if: env.RUN_ID == 0
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - name: Set up poetry
        if: env.RUN_ID == 0
        run: poetry install
      - name: Post to The Lytton Tribune
        if: env.RUN_ID == 0
        run: poetry run python lytton.py
        env:
          BSKY_BASE_URL: ${{ secrets.BSKY_BASE_URL }}
          LYTTON_BSKY_HANDLE: ${{ secrets.LYTTON_BSKY_HANDLE }}
          LYTTON_BSKY_PASSWORD: ${{ secrets.LYTTON_BSKY_PASSWORD }}
          LYTTON_MASTO_ACCESS_TOKEN: ${{ secrets.LYTTON_MASTO_ACCESS_TOKEN }}
          MASTO_BASE_URL: ${{ secrets.MASTO_BASE_URL }}
