name: "🚀 Now This Is Podracing"

on:
  schedule:
    - cron: "57 */3 * * *"

env:
  RUN_ID: -1
  RUN_TIMING: 3

jobs:
  post_podracing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate timing
        run: |
          echo "RUN_ID=$((${{ github.run_number }} % $RUN_TIMING))" >> "$GITHUB_ENV"
      - name: Install poetry
        if: env.RUN_ID == 0
        run: pipx install poetry
      - name: Set up Python
        if: env.RUN_ID == 0
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - name: Set up poetry
        if: env.RUN_ID == 0
        run: poetry install
      - name: Post to Not Podracing
        if: env.RUN_ID == 0
        run: poetry run python not-podracing.py
        env:
          BSKY_BASE_URL: ${{ secrets.BSKY_BASE_URL }}
          MASTO_BASE_URL: ${{ secrets.MASTO_BASE_URL }}
          PODRACING_BSKY_HANDLE: ${{ secrets.PODRACING_BSKY_HANDLE }}
          PODRACING_BSKY_PASSWORD: ${{ secrets.PODRACING_BSKY_PASSWORD }}
          PODRACING_MASTO_ACCESS_TOKEN: ${{ secrets.PODRACING_MASTO_ACCESS_TOKEN }}
          WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
