name: "The Lytton Tribune"

on: workflow_dispatch

jobs:
  post_lytton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - run: poetry install
      - name: Post to The Lytton Tribune
        run: poetry run python lytton.py
        env:
          BSKY_BASE_URL: ${{ secrets.BSKY_BASE_URL }}
          LYTTON_BSKY_HANDLE: ${{ secrets.LYTTON_BSKY_HANDLE }}
          LYTTON_BSKY_PASSWORD: ${{ secrets.LYTTON_BSKY_PASSWORD }}
          LYTTON_MASTO_ACCESS_TOKEN: ${{ secrets.LYTTON_MASTO_ACCESS_TOKEN }}
          MASTO_BASE_URL: ${{ secrets.MASTO_BASE_URL }}
